import { Geist, Geist_Mono, Inter } from "next/font/google";
import "@/assets/styles/globals.css";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased`} >
          <ThemeProvider
          attribute='class'
          defaultTheme='system'
          value={{light: "light", dark: "dark", system: "system"}} // This will set the light and dark themes
          enableSystem 
          disableTransitionOnChange>
            {children}
          </ThemeProvider>   
      </body>
    </html>
  );
}
